### PR TITLE
feat: add FM project

### PR DESCRIPTION
**Pull request by jybai**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by OctoberChang** [comment]
@jybai , thanks for creating the pull request.

Here are some suggestions before merge:
- We need to pin down the dependencies (e.g., `libpecos` version), as your code depends on the c/c++ libraries in pecos folder.
- We can not include binary pdf files (i.e., `FM_O_dk.pdf`). You can write math equations in Github readme markdown, or attach a hyper-link to the pdf stored on other cloud storages.

Let me know if you have time to address it. Otherwise, I will close this pull request.

**Comment by jybai** [comment]
@OctoberChang Thank you for your prompt reply. I think I'd be able to fix it. The pdf part is simple. Regarding the dependency, I'm not sure what exactly should I do. Should I specify which version of pecos is used in the README?

**Comment by OctoberChang** [comment]
> @OctoberChang Thank you for your prompt reply. I think I'd be able to fix it. The pdf part is simple. Regarding the dependency, I'm not sure what exactly should I do. Should I specify which version of pecos is used in the README?

1. Here are an example you can put into Install Section of the README.md.
```
# git clone with a specific release tag v0.4.0
git clone -b v0.4.0 https://github.com/amzn/pecos.git;
cd pecos/example/fm;
make all
```

2. Another suggestion is the folder name `fm` could be a bit ambiguous. Can you rename it to more specific one, such as `fm-for-xmc` ?

**Comment by jybai** [comment]
@OctoberChang I have updated the directory name, README, and FM complexity doc file according to suggestions. Please let me know if anything else needs fixing. Many thanks.

**Review by OctoberChang — APPROVED** [review]

**Pull request merged**
